### PR TITLE
making go style comments work in templ

### PR DESCRIPTION
**Pull request by BKR-dev**
hey, 

I found that the go comments are not correctly displayed so I talked to @valxntine and he showed me the different grammars. anyway I think I found the correct pattern that matches the go style comments but to be honest I never worked on any of this before so I don't know if I can just add this or how to verify that its working and not braking it. 

so please just takes this as a little helpful try from somebody who doesn't know but wants to help. 

if you or anybody else can point me towards how to test it I'd be happy to make it work on my own, but without guidance im kinda lost. 

hope this helps & thanks for this project!

### CODE REVIEW

**Comment by vrischmann** [comment]
Hi,

thanks for your contribution. 

It's relatively easy to add tests for the parser but first you need to setup your environment; the official [tree-sitter documentation](https://tree-sitter.github.io/tree-sitter/creating-parsers#getting-started) is good enough for this. You only need the `tree-sitter` binary.

Tests are written as text files in the `corpus` directory, again the [tree-sitter documentation](https://tree-sitter.github.io/tree-sitter/creating-parsers#command-test) is great to get an idea of how it works. You can run them with `tree-sitter test`.

So for this modification I think you could just add a test in [corpus/go.txt](https://github.com/vrischmann/tree-sitter-templ/blob/master/corpus/go.txt) file that verifies comment parsing works and there are no regressions and it should be good enough.

**Comment by BKR-dev** [comment]
thanks for takign the time to spell it out for me! 

i think the test is now accurate but it is not passing. can you take a look if you have the time? from what i read in the docs it should reflect the change that i added to the grammar. when i generate it its missing the go-grammar part. im not sure im on the right track.

**Comment by vrischmann** [comment]
so I looked into it, unfortunately you're hitting some annoying stuff with the `$.element_text` external node which is handled in C (in the `scanner.c` file). 
I'll look into it more but now that I have my eyes on the grammar again I think it's going to need a different approach.

**Comment by vrischmann** [comment]
Ok I made it work. If you're ok with it I will squash your commits and add my commits on top to your PR with the fixes needed.

The test in `corpus/go.txt` had some issues but anyway the parser won't work without a modification to the scanner as I said before. Basically the `$.element_text` token is matched before the `$.go_comment` token, I've had to modify the scanner.

**Comment by valxntine** [comment]
I could be wrong here but do we actually need `go_comment` in the grammar? We're effectively inheriting from the Go grammar which already defines the comment, and that is passing in the tests where it's outside of the component blocks, and the tests pass using `(comment)` for that one which I believe is the definition made in the Go grammar. So I think once the parser is fixed, `go_comment` _could_ be removed and just replaced in the tests with `comment`?

**Comment by vrischmann** [comment]
> I could be wrong here but do we actually need `go_comment` in the grammar? We're effectively inheriting from the Go grammar which already defines the comment, and that is passing in the tests where it's outside of the component blocks, and the tests pass using `(comment)` for that one which I believe is the definition made in the Go grammar. So I think once the parser is fixed, `go_comment` _could_ be removed and just replaced in the tests with `comment`?

I actually tried that but for some reason if I use the inherited `$.comment` there's an error :/ Unfortunately I don't have enough knowledge of tree-sitter to understand why.

**Comment by valxntine** [comment]
Ahh okay, that's a shame. I don't know much about tree-sitter either but reading the docs it has a concept of precedence, is there any way we can just assign the comment a higher precedence than the rest of the elements in a component block? 
https://tree-sitter.github.io/tree-sitter/creating-parsers#:~:text=in%20EBNF%20notation.-,Precedence,-%3A%20prec(number

**Comment by vrischmann** [comment]
`prec.right(1, $.comment)` works actually. 

The branch [go-comments](https://github.com/vrischmann/tree-sitter-templ/tree/go-comments) contains my fixes. @BKR-dev either you can include the fixes in your PR or if you're ok with it I'll add my commits to your PR.

**Comment by BKR-dev** [comment]
@vrischmann sure thing go ahead and add your commits, I'm not within computer reach and as you guys are on fire I don't wanna slow things down 😂

**Pull request merged**
