### PR TITLE
Fix inconsistencies

### LINKED ISSUE #24: Inconsistency between $.element, $.style_element and $.script_element
Investigating #22 and implementing #23 made me realize we have some inconsistencies between `$.element`, `$.style_element` and `$.script_element`.

An standard element creates these nodes:
```
<div></div>

(element
  (tag_start
    name: (element_identifier))
  (tag_end
    name: (element_identifier)))
```

a style element (normal or self-closing) creates these nodes:
```
<style></style>
<style />

(style_element)
(style_element)
```

a script element (normal or self-closing) creates these nodes:
```
<script></script>
<script />

(script_element)
(script_element)
```

We have no way to know if a style or script element is for a tag_start/tag_end tuple or a self-closing tag, and I think we should have one.

I'm thinking style_element and script_element should produce `tag_start` and `tag_end` nodes but I don't know if I can do that without introducing a conflict.

If the name needs to be unique we could use `style_tag_start`, `style_tag_end`, `script_tag_start` and `script_tag_end`. That will require an update the nvim-treesitter queries though.

I'll have to experiment.

### PR DESCRIPTION
**Pull request by vrischmann**
Modify the grammar so that `style_element` is composed of a `style_tag_start` and `style_tag_end` just like a regular `element` is.

So for example instead of having this:
```
(style_element
  (attribute
    name: (attribute_name)
    value: (quoted_attribute_value
      (attribute_value)))
  (style_element_text))
```

we now have this:
```
(style_element
  (style_tag_start
    (attribute
      name: (attribute_name)
      value: (quoted_attribute_value
        (attribute_value))))
  (style_element_text)
  (style_tag_end))
```

While not strictly necessary for proper syntax highlighting as far as I can tell, it makes more sense semantically to have attributes be under the `style_tag_start` instead of the whole element.

This fixes #24.

The current nvim-treesitter queries still work fine because the `style_element` hasn't been removed but just to be consistent I'll add [this small patch](https://github.com/nvim-treesitter/nvim-treesitter/commit/e46017c02aeb2e5cd241196a2048b4c1e88002cc) upstream.

### CODE REVIEW

**Comment by vrischmann** [comment]
Hi @danderson. Could you let me know if you need to change anything in the emacs package for this change ? Thank you !

**Comment by danderson** [comment]
Thanks for making this change! I can test later today hopefully, it should be an easy fix :crossed_fingers: The main thing I have to figure out is how to query for which grammar variant people have installed, so that I can adapt the queries. I wish treesitter grammars included version info :(

**Comment by vrischmann** [comment]
> Thanks for making this change! I can test later today hopefully, it should be an easy fix 🤞 The main thing I have to figure out is how to query for which grammar variant people have installed, so that I can adapt the queries. I wish treesitter grammars included version info :(

I'm not familiar with how it works in the emacs world but do you not bind the queries to a specific parser version ? 

nvim-treesitter does this by having the git hash of the parser in a lock file so when people update nvim-treesitter with the new queries they'll automatically update the parser as well.

**Comment by vrischmann** [comment]
Hey @danderson, any news on your part ? I'm thinking of merging this as is because as far as I understand since there are no query changes necessary it won't affect the emacs package.

**Pull request merged**
